Repository nomad-coe/electronic-parsers, pull requests merged in 2023-04, with the labels that each got.

#72 Rework GW and BSE method
  electronicparsers/abinit/parser.py
  electronicparsers/exciting/metainfo/exciting.py
  electronicparsers/exciting/parser.py
  electronicparsers/fhiaims/parser.py
  electronicparsers/ocean/parser.py
  electronicparsers/utils/utils.py
  electronicparsers/vasp/parser.py
  tests/test_abinitparser.py
  tests/test_excitingparser.py
  tests/test_fhiaimsparser.py
  tests/test_oceanparser.py
  tests/test_vaspparser.py
Labels: refactor

#63 57 molecular dynamics support for fhiaims
  electronicparsers/fhiaims/metainfo/fhi_aims.py
  electronicparsers/fhiaims/parser.py
  tests/test_fhiaimsparser.py
Labels: enhancement

#81 Implement flag for `pytest` interaction with VS code
  tests/conftest.py
Labels: enhancement

#80 Frequency and time meshes
  electronicparsers/abinit/parser.py
  electronicparsers/exciting/parser.py
  electronicparsers/fhiaims/parser.py
  electronicparsers/soliddmft/parser.py
  electronicparsers/vasp/parser.py
  electronicparsers/w2dynamics/parser.py
  tests/test_abinitparser.py
  tests/test_excitingparser.py
  tests/test_fhiaimsparser.py
  tests/test_soliddmft.py
  tests/test_vaspparser.py
  tests/test_w2dynamicsparser.py
Labels: refactor

#85 Optimize w2dynamics
  electronicparsers/w2dynamics/metainfo/w2dynamics.py
  electronicparsers/w2dynamics/parser.py
  electronicparsers/wannier90/parser.py
  tests/test_w2dynamicsparser.py
Labels: documentation, enhancement

#83 Update bandgap
  electronicparsers/abinit/metainfo/abinit.py
  electronicparsers/abinit/parser.py
  electronicparsers/ams/parser.py
  electronicparsers/exciting/parser.py
  electronicparsers/vasp/parser.py
  tests/test_excitingparser.py
Labels: refactor

#89 BSE changes
  electronicparsers/exciting/parser.py
  electronicparsers/ocean/parser.py
  electronicparsers/soliddmft/parser.py
  tests/test_oceanparser.py
Labels: bug, feature / enhancement
